# This file was generated by GoReleaser. DO NOT EDIT.
cask "easy-cd" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ecd"]
    end
  end

  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "62d187afa6814d2d41563be842fa155241fdbe089cf2f09c335b7a66ae65de01"
      url "https://github.com/banozz0/easy-cd/releases/download/v#{version}/easy-cd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f0646cac9c0d7c1073bb5432663ceb1d8b007dbd582b86af1f95960afbd6a315"
      url "https://github.com/banozz0/easy-cd/releases/download/v#{version}/easy-cd_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a906da0bcea299e8d453e58f9d86e68a93ca674f6390496af1d9782b9293d972"
      url "https://github.com/banozz0/easy-cd/releases/download/v#{version}/easy-cd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a1d44c0191e2d46df82721b8bf50e90a5a5f9f52689c47a2021911d3d0948fa6"
      url "https://github.com/banozz0/easy-cd/releases/download/v#{version}/easy-cd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "easy-cd"
  desc "Terminal folder picker: arrow keys to walk, type to search, Enter to cd"
  homepage "https://github.com/banozz0/easy-cd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ecd"

  # No zap stanza required

  caveats <<~EOS
    Add eval "$(ecd init zsh)" (or bash, or fish) to your shell's config.
    Run ecd init to see the exact line and file for each shell.
  EOS
end
