# This file was generated by GoReleaser. DO NOT EDIT.
cask "easy-cd" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ecd"]
    end
  end

  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "faa681c658b266d060cfa8c883250b9d3518a4ef345add125e6a249fdca1f150"
      url "https://github.com/banozz0/easy-cd/releases/download/v#{version}/easy-cd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f404ba068e261912fc463d1f4a0fb50bd341d61d15efec4d59edd2d00b126122"
      url "https://github.com/banozz0/easy-cd/releases/download/v#{version}/easy-cd_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "147ba626fa32896cd656b680edbaed8a8da81399df381d470047ebad8f6574af"
      url "https://github.com/banozz0/easy-cd/releases/download/v#{version}/easy-cd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2578b41f07ec740627387f4fc3e048f30a7b33ec9ac3f31c34e1a4f7afadc22b"
      url "https://github.com/banozz0/easy-cd/releases/download/v#{version}/easy-cd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "easy-cd"
  desc "Terminal folder picker: arrow keys to walk, type to search, Enter to cd"
  homepage "https://github.com/banozz0/easy-cd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ecd"

  # No zap stanza required

  caveats <<~EOS
    Add eval "$(ecd init zsh)" (or bash, or fish) to your shell's config.
    Run ecd init to see the exact line and file for each shell.
  EOS
end
