# This file was generated by GoReleaser. DO NOT EDIT.
cask "easy-cd" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "841bbc980c073f3bd994bcb1bbf96e9094b3a7ce645a53fe3d4303158681a1b3"
      url "https://github.com/banozz0/easy-cd/releases/download/v#{version}/easy-cd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "60fd45bd1ac95ef553f810604faba4b5d778db57bd177e45e79f15d8afd3be8d"
      url "https://github.com/banozz0/easy-cd/releases/download/v#{version}/easy-cd_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3c5e3a61316682620dcc4320cda145d59708200eb06af20164ff7d188cf8fced"
      url "https://github.com/banozz0/easy-cd/releases/download/v#{version}/easy-cd_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eb4a234e807fbac42b6e42bfbcfb0c91b82c47b773ba969b177f6c709cb86c8e"
      url "https://github.com/banozz0/easy-cd/releases/download/v#{version}/easy-cd_#{version}_linux_amd64.tar.gz"
    end
  end

  name "easy-cd"
  desc "Terminal folder picker: arrow keys to walk, type to search, Enter to cd"
  homepage "https://github.com/banozz0/easy-cd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ecd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ecd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Add eval "$(ecd init zsh)" (or bash, or fish) to your shell's config.
    Run ecd init to see the exact line and file for each shell.
  EOS
end
